### PR TITLE
Rebuild extension for Thunderbird 128+ (MV3)

### LINKED ISSUE #5: Displaying decrypted e-mails
After decryption the folder displayed switched to `Postguard Received`, however the e-mail is not selected and shown.

### LINKED ISSUE #14: Requires too many permissons from TB
Warning that PostGuard will have full, unrestricted access to your computer

When installing the AddOn I'm warned that PostGuard needs "full, unrestricted access to Thunderbird and your computer". Which obviously sounds scary.

Accoding to [Thunderbird documentation]([https://support.mozilla.org/nl/kb/toestemmingsaanvraagberichten-voor-extensies-tb#w_volledige-onbeperkte-toegang-[…]erbird-en-uw-computer-verkrijgen](https://support.mozilla.org/nl/kb/toestemmingsaanvraagberichten-voor-extensies-tb#w_volledige-onbeperkte-toegang-tot-thunderbird-en-uw-computer-verkrijgen)) this is fixable by upgrading to a more modern extension API.

### LINKED ISSUE #27: Yarn compiler build warnings
```
/Users/rubenhensen/Repos/postguard-tb-addon/src/background/background.ts
   12:24  warning  'ISigningKey' is defined but never used   @typescript-eslint/no-unused-vars
   70:14  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   79:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  604:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  609:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  749:57  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  765:57  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  765:71  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/rubenhensen/Repos/postguard-tb-addon/src/experiments/notificationbar/implementation.js
    7:7   warning  'ExtensionError' is assigned a value but never used   @typescript-eslint/no-unused-vars
  354:5   warning  'notificationbar' is assigned a value but never used  @typescript-eslint/no-unused-vars
  372:23  warning  'aTopic' is defined but never used                    @typescript-eslint/no-unused-vars
  372:31  warning  'aData' is defined but never used                     @typescript-eslint/no-unused-vars

/Users/rubenhensen/Repos/postguard-tb-addon/src/experiments/pg4tb/pg4tb-impl.ts
    5:11  warning  'Components' is defined but never used    @typescript-eslint/no-unused-vars
   86:30  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   93:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  118:47  warning  'parent' is defined but never used        @typescript-eslint/no-unused-vars
  118:55  warning  'child' is defined but never used         @typescript-eslint/no-unused-vars
  118:62  warning  Unexpected empty method 'onFolderAdded'   @typescript-eslint/no-empty-function
  142:46  warning  'messageId' is defined but never used     @typescript-eslint/no-unused-vars
  142:57  warning  Unexpected empty method 'GetMessageId'    @typescript-eslint/no-empty-function
  143:44  warning  'progress' is defined but never used      @typescript-eslint/no-unused-vars
  143:54  warning  'progressMax' is defined but never used   @typescript-eslint/no-unused-vars
  143:67  warning  Unexpected empty method 'OnProgress'      @typescript-eslint/no-empty-function
  144:47  warning  Unexpected empty method 'OnStartCopy'     @typescript-eslint/no-empty-function

/Users/rubenhensen/Repos/postguard-tb-addon/src/experiments/switchbar/implementation.js
  380:5   warning  'switchbar' is assigned a value but never used  @typescript-eslint/no-unused-vars
  398:23  warning  'aTopic' is defined but never used              @typescript-eslint/no-unused-vars
  398:31  warning  'aData' is defined but never used               @typescript-eslint/no-unused-vars

/Users/rubenhensen/Repos/postguard-tb-addon/src/utils.ts
  42:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 28 problems (0 errors, 28 warnings)
```

### LINKED ISSUE #28: Update dependencies
```
[1/4] 🔍  Resolving packages...
⠁ (node:11501) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
warning grunt-ts > chokidar > fsevents@1.2.13: Upgrade to fsevents v2 to mitigate potential security issues
```

Also yivi frontend packages to v2 for better qr codes

### LINKED ISSUE #31: Postguard will not install on latest Thunderbird
PostGuard (beta) kon niet worden geinstallerd, omdat het niet compatibel is met Thunderbird 148.0

### LINKED ISSUE #32: Rebuild extension for Thunderbird 128+ (MV3)
## Problem

The current PostGuard Thunderbird extension is broken on Thunderbird 128+ due to:
- `Services.jsm` removed (replaced by `Services.sys.mjs`)
- `pg4tb` experiment API uses deprecated `copyFileMessage()` 
- MV2 manifest, Grunt/Webpack/Svelte3 build system
- Various dead code paths for TB < 112

The extension has been non-functional on modern Thunderbird versions.

## Solution

Complete rebuild from scratch using modern Thunderbird standards:

- **Manifest V3** targeting Thunderbird 128+
- **TypeScript + esbuild** build system (replaces Grunt/Webpack/Svelte)
- **No experiment APIs** — uses standard `scripting.messageDisplay`, `composeAction`, `compose.onBeforeSend`
- **@e4a/pg-wasm 0.4.0** with custom WASM loader for Thunderbird context
- **Yivi QR popup** with direct IRMA server polling (replaces Yivi client library)

### What's implemented:
- Compose action button with encryption toggle per tab
- Policy editor popup for per-recipient Yivi attribute selection
- Signing identity editor
- Full encryption flow via `compose.onBeforeSend` with keepalive pattern
- Message display content script with decrypt banner
- Full decryption flow (Yivi authentication → USK retrieval → unseal)
- JWT caching with automatic cleanup
- Sent folder plaintext copy management
- English and Dutch localization

### Architecture:
- `background.ts` — Main orchestrator (all event listeners, encrypt/decrypt flows)
- `src/lib/` — Modular libraries (pkg-client, encryption, decryption, MIME builder, JWT store)
- `src/content/` — Message display content script (banner injection)
- `src/pages/` — Popup windows (compose action, policy editor, Yivi QR)
- `public/pg-wasm/load.js` — Custom WASM loader for Thunderbird CSP

### LINKED ISSUE #40: Replace encrypted email with decrypted email in-place
## Problem

Currently, after decryption the extension imports the decrypted message as a new email and deletes the encrypted original. This causes the user to be redirected to a different message, losing their place. The decrypted message may also end up with a different message ID, breaking threading and conversation view.

## Expected Behavior

When the user clicks "Decrypt":
1. The encrypted email should be replaced **in-place** in the same message view
2. The message body should update to show the decrypted content
3. Attachments from the encrypted payload should appear as normal attachments
4. The message should remain in the same folder, same position, same thread
5. The subject line should update from "PostGuard Encrypted Email" to the original subject
6. The user should not be navigated away — the current view simply refreshes with decrypted content

## Current Behavior

- A new message is imported via `messages.import()`
- The original encrypted message is deleted
- The user is navigated to the new message
- Thread continuity may be broken

## Considerations

- Thunderbird's `messages.update()` API may allow modifying the message in-place
- Alternatively, the imported message needs to preserve the original's `Message-ID` and `References`/`In-Reply-To` headers to maintain threading
- The `X-PostGuard` header should be preserved so the extension knows it was originally encrypted

### LINKED ISSUE #41: Preserve email threading for encrypted messages
## Problem

Encrypted PostGuard emails break email conversation threading in multiple ways:

1. **Subject changes** — The encrypted email has subject "PostGuard Encrypted Email" instead of the original subject (e.g., "Re: Meeting notes"). Thunderbird's thread view groups by subject, so the encrypted email falls out of the conversation.

2. **Decrypted message loses thread position** — After decryption, the new imported message may not retain the correct `In-Reply-To` and `References` headers, so it doesn't get placed back into the original thread.

3. **Reply to encrypted email** — When replying to a still-encrypted message, the reply should thread correctly with the conversation, not start a new thread under "Re: PostGuard Encrypted Email".

## Expected Behavior

- An encrypted email sent as part of a conversation should appear in that conversation thread
- After decryption, the decrypted message should remain in the same thread position
- Replies to encrypted (or decrypted) messages should continue the original thread
- The conversation view should look natural, as if encryption was transparent

### Sending
- Preserve `In-Reply-To` and `References` headers in the outer encrypted envelope (not just inside the encrypted MIME)
- Consider keeping the original subject (or `Re: Original Subject`) on the outer envelope instead of replacing it with "PostGuard Encrypted Email" — the subject is not secret (it's visible in the inner MIME anyway) and preserving it maintains threading

### Decryption
- When importing the decrypted message, ensure it carries the same `Message-ID`, `In-Reply-To`, and `References` headers as the encrypted original
- This ties into #40 (in-place replacement) — if the decrypted message replaces the original in-place, threading is automatically preserved

## Related

- #40 — Replace encrypted email with decrypted email in-place

### LINKED ISSUE #42: Remove or gate debug console.log statements
## Problem

The codebase currently has many `console.log` and `console.error` debug statements (e.g., `[PostGuard] queryMessageState called, tabId:`, `[PostGuard] Recipients type:`, etc.) that were added during development and debugging. These should not ship in a production release.

## Solution

- Remove debug-only logging (recipient dumps, sender info, state results)
- Keep meaningful operational logs (startup, errors, warnings) but gate verbose ones behind a debug flag or remove entirely
- Consider a simple log level system: `console.error` always, `console.warn` for recoverable issues, `console.log` only in development

## Related

- #37 — Publish extension to Thunderbird Add-ons store

### LINKED ISSUE #47: Sent copy fails after sending encrypted email
## Problem

After sending an encrypted email, Thunderbird sometimes shows an error dialog:

> **Bericht opslaan**
> Uw bericht is verzonden, maar door netwerkproblemen of fouten met de bestandstoegang is er geen kopie in uw map voor verzonden berichten (Sent Items) geplaatst.
> U kunt het opnieuw proberen of het bericht lokaal opslaan in Lokale mappen/Sent Items-ruben@hensen.io.

Translation: "Your message was sent, but due to network problems or file access errors, no copy was placed in your Sent Items folder."

The email is sent successfully, but the sent copy management fails.

## Likely Cause

The `compose.onAfterSend` handler tries to:
1. Import a plaintext copy via `messages.import()`
2. Move it to the sent folder
3. Delete the encrypted copy from sent

This may conflict with Thunderbird's own sent copy mechanism, or the timing of these operations may cause file access issues on the IMAP server. The encrypted message that Thunderbird tries to save to Sent may also be larger than the IMAP server allows, triggering the error before our `onAfterSend` handler even runs.

## To investigate

- Does this happen consistently or intermittently?
- Is it related to message size?
- Is the `onAfterSend` handler interfering with Thunderbird's built-in sent copy?
- Should we disable Thunderbird's own sent copy for encrypted messages and handle it entirely ourselves?

### PR DESCRIPTION
**Pull request by rubenhensen**
## Summary

Complete rewrite of the PostGuard Thunderbird extension for modern Thunderbird (128+).

- **Manifest V3** with standard WebExtension APIs (no experiment APIs)
- **TypeScript + esbuild** build system (replaces Grunt/Webpack/Svelte)
- **Custom WASM loader** for pg-wasm in Thunderbird CSP context
- **Yivi QR popup** with direct IRMA server polling
- **Full encrypt/decrypt flows** with JWT caching
- **English and Dutch** localization

### Architecture
- `background.ts` — Main orchestrator with MV3 keepalive pattern
- `src/lib/` — Modular libraries (PKG client, encryption, decryption, MIME, JWT store)
- `src/content/` — Message display content script (decrypt banner)
- `src/pages/` — Popup windows (compose action, policy editor, Yivi QR)

### Reply-to-encrypted detection
- Auto-enable encryption when replying to a previously-decrypted message (`wasPGEncrypted` check via `X-PostGuard` header)
- Inject `X-PostGuard` header into decrypted messages for reply detection
- Fix `mailTabs.setSelectedMessages` to use correct tab ID signature
- Fix folders API calls to use folder ID instead of account object
- Handle `"local"` account type in addition to `"none"` for Local Folders

### Email threading preservation
- Inject `In-Reply-To`/`References` from encrypted envelope into decrypted MIME so decrypted messages stay in their original thread
- Include threading headers in inner MIME when sending encrypted replies
- Add `injectMimeHeaders()` helper for safe MIME header manipulation
- Fix `messages.move()` to pass folder ID instead of `MailFolder` object

### Debug logging
- Gate `console.log` behind dev/release builds using esbuild `pure` annotation
- Release builds (`npm run build`) strip all `console.log` and minify output
- Dev builds (`npm run build:dev`, `npm run watch`) retain all logging

## Test plan
- [x] `npm run build` succeeds
- [x] Load `dist/manifest.json` in Thunderbird via about:debugging
- [x] Compose → enable PostGuard → set policy → send encrypted email
- [x] Open encrypted email → see decrypt banner → click Decrypt → Yivi QR → see plaintext
- [x] JWT caching works (second decrypt skips Yivi)
- [x] Reply to decrypted email auto-enables encryption
- [x] Decrypted messages stay in their original thread
- [x] Encrypted replies preserve threading headers
- [x] Release build has 0 `console.log`, keeps `console.warn`/`console.error`
- [x] Dev build retains all `console.log` calls

Closes #32, closes #31, closes #14, closes #40, closes #41, closes #42, closes #47, closes #5, closes #27, closes #28

### CODE REVIEW

File: src/pages/policy-editor/policy-editor.ts [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+
+interface InitData {
+  initialPolicy: Record<string, Array<{ t: string; v: string }>>;
+  sign: boolean;
+}
+
+const ATTRIBUTE_TYPES = [
+  { type: "pbdf.sidn-pbdf.email.email", label: "Email address", hasValue: true },
+  { type: "pbdf.sidn-pbdf.mobilenumber.mobilenumber", label: "Mobile number", hasValue: true },
+  { type: "pbdf.gemeente.personalData.surname", label: "Surname", hasValue: true },
```
Comment (w-ensink) [inline src/pages/policy-editor/policy-editor.ts]: Do we want the passport, id-card and drivinglicence here too? And are the AGB code and surfnet id still used/relevant?
